MainMenu_Name: 'Main Menu'
Create: 'Create An Armor Stand'
Close: 'Close Menu'
CustomMenu_Name: 'Custom Your Armor Stand'
MainHand: 'Choose The Weapon Of The Main Hand'
OffHand: 'Choose The Weapon Of The Off Hand'
Head: 'Choose The Head'
Armor: 'Choose The Armor'
Position: 'Choose The Position'
Confirm: 'Confirm And Spawn'
Cancel: 'Cancel Process'
